kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: run-nutanixabs-provisioner
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: nutanixabs-provisioner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: nutanixabs-provisioner-runner
  apiGroup: rbac.authorization.k8s.io
