apiVersion: v1
kind: Secret
metadata:
  name: ntnx-secret
  namespace: kube-system
data:
  # base64 encoded admin:password. E.g.: echo -n "admin:mypassword" | base64
  key: {{ default "" .Values.password | b64enc | quote }}
type: nutanix/abs
