kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: silver
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  namespace: kube-system
provisioner: nutanix/abs
parameters:
     prismEndPoint: {{ .Values.prismEndPoint }}
     dataServiceEndPoint: {{ .Values.dataServiceEndPoint }}
     user: {{ .Values.user }}
     secretName: ntnx-secret
     storageContainer: {{ .Values.storageContainer }}
     fsType: {{ .Values.fsType }}
     chapAuthEnabled: {{ .Values.chapAuthEnabled }}
